# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saji Shunnarah | Software Engineer
email: sajishunnarah@gmail.com
description: >-
  Portfolio of Saji Shunnarah - Passionate software engineer specializing in full-stack development,
  cloud architecture, and building innovative solutions. Creator of Rezumake. Explore my projects and technical expertise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rezumake.com" # the base hostname & protocol for your site
github_username: sajishunnarah
linkedin_username: sajishunnarah

# Author information
author:
  name: Saji Shunnarah
  email: sajishunnarah@gmail.com
  bio: Passionate Software Engineer | Full-Stack Developer | Problem Solver

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
lang: en_US
timezone: America/New_York

# Social media
social:
  name: Saji Shunnarah
  links:
    - https://github.com/rtseuztz
    - https://linkedin.com/in/sajishunnarah

# Collections
collections:
  posts:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Saji Shunnarah"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
